- name: Install network manager
  become: true
  apt:
    name:
      - network-manager
      - network-manager-gnome
    state: latest
    update_cache: yes
  tags: network

- name: Enable network manager
  become: true
  ansible.builtin.systemd_service:
    name: NetworkManager
    state: started
    enabled: true
  tags: network
