- name: Install packages (brew)
  block:
    - name: Install taps
      command: /home/linuxbrew/.linuxbrew/bin/brew tap {{ item }}
      args:
        creates: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/{{ item }}
      loop:
        - wez/wezterm-linuxbrew

    - name: Install packages
      command: /home/linuxbrew/.linuxbrew/bin/brew install {{ item }}
      args:
        creates: /home/linuxbrew/.linuxbrew/opt/{{ item }}
      loop:
        - wezterm
