- name: Install Nix
  shell: |
    set -o pipefail &&
    curl -L https://nixos.org/nix/install | sh -s -- --daemon
  args:
    executable: /bin/bash
    creates: "/nix/var/nix/profiles/default/bin/nix"
