- name: Install packages (apt)
  become: true
  apt:
    name:
      - software-properties-common
      - libfuse2 # needed for running appimages
      # ↓ needed for Homebrew: https://docs.brew.sh/Homebrew-on-Linux#requirements
      - build-essential
      - procps
      - curl
      - file
    state: latest
    update_cache: yes

- name: Install packages (brew)
  block:
    - name: Install taps
      command: /home/linuxbrew/.linuxbrew/bin/brew tap {{ item.name }}
      args:
        creates: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/{{ item.dirname }}
      loop:
        - { name: wez/wezterm-linuxbrew, dirname: wez/homebrew-wezterm-linuxbrew }

    - name: Install packages
      command: /home/linuxbrew/.linuxbrew/bin/brew install {{ item }}
      args:
        creates: /home/linuxbrew/.linuxbrew/opt/{{ item }}
      loop:
        - wezterm
