- name: Install Nix Package Manager [1/3]
  shell: |
    set -o pipefail &&
    curl -L https://nixos.org/nix/install | sh -s -- --daemon
  args:
    executable: /bin/bash
    creates: "/nix/var/nix/profiles/default/bin/nix"

- name: Install Nix Package Manager [2/3]
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/nix/nix.conf"
    line: experimental-features = nix-command flakes
    create: true

- name: Install Nix Package Manager [3/3]
  become: true
  ansible.builtin.systemd_service:
    name: nix-daemon
    state: restarted
  changed_when: false
