- name: Install window manager
  become: true
  apt:
    name:
      - xorg
      - awesome
    state: latest
    update_cache: yes

- name: Disable display manager
  become: true
  block:
    - name: Get current systemd default
      command: systemctl get-default
      changed_when: false
      register: systemdefault

    - name: Set default to multi-user target
      command: systemctl set-default multi-user
      when: "'graphical' in systemdefault.stdout"
  tags: x11

- name: Set mouse options
  become: true
  ansible.builtin.blockinfile:
    path: /usr/share/X11/xorg.conf.d/99-mouse.conf
    block: |
      Section "InputClass"
        Identifier "libinput pointer mouse"
        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Accel Profile Enabled" "0 1 0"
        Option "Accel Speed" "-0.8"
      EndSection
    insertafter: EOF
    state: present
    create: true
  tags: x11